### ISSUE TITLE
마일스톤에 대한  의견

### ISSUE THREAD

**Issue by oldiron-ho** [9hobbes/h-draft#1]
쓰다보니 마일스톤 보다는 개발 순서에 대한 일반적인 기술이 돼 버리네요.
아직 기획이나 설계가 마무리 되지 않은 상태에서 개발 과정에 대한 마일스톤을 자세히 적는다는
것에 모순이 있는 것 같기도 하고, 이게 빠지면 아무 프로젝트에나 적용되는 형식적 마일스톤이
되어 버리는 거 같습니다.
실제, 개발 과정의 순서라는 것은 백로그의 목록에서 우선순위를 정하고 그에 따라 단계를 나눌 수 있는 
것인데 그 단계를 밟지 않는 현재 상황에서 기술하는 것이 의미가 있나 생각이 듭니다.

| 단계 | 해야할 일 | 버전 관리 | 
| --- | --- | --- |
| 기획 | 기능명세 작성 <br> 유저 스토리 기술 |  X |
| 설계 |  h-draft 구성 요소 정의 <br> 구성요소의 기능 정의 <br>구성 요소간 동작관계 정의 | X |
| 개발 준비 | 백로그 작성 <br> 백로그 우선순위 선정 | X |  
| 모듈 생성 |  기본 구성 요소간 인터페이스 정의와 최소 기능 개발 | X |
| 모듈 연결 |  모듈 연결 | 0.1.x |
| 기능 개발 | 백로그의 우선 순위에 따라 모듈의 기능을 구현 | ?? |

**Comment by 9beach** [comment]
마일스톤을 작성할 때 보편적으로 발생하는 문제라 이 기회에 정리할 필요가 있을 것 같다. 대부분 레퍼런스가 있는 말을 할 테지만 나도 확신할 수 없는 부분은 따로 언급할게.

* 기획은 개발 계획은 사전 단계이기 때문에 개발 계획의 대상이 아니다.
* 기능 명세 작성과 유저 스토리 기술은 기획의 범위가 아니다.
* 백로그 작성과 백로그 우선 순위 선정은 메타적 활동이라 계획에 넣으면 많은 논리적 난점이 발생한다. 억지로 예를 지어내면 마일스톤 리비전도 넣어야겠지. 그러나 그러한 활동은 별개로 취급한다. 즉 프로젝트 진행, 프로젝트 매니지먼트, 프로젝트 사전단계를 섞어서 생각하는 것이 흔히 실수하는 오류다. 다양한 원인이 있는데, 논리적 혼동, 관료주의(우리 회사도 저거를 마일스톤 양식에 넣었는데 이유를 파악하니 관리적 활동을 별도로 진행하지 않고 개발 계획에 묻어가려는 관료주의 때문이라는 게 현재 내 결론) 등 다양하다.

너의 질문 중 일반적으로 오해되는 핵심 이유가 나오는데 그것이 바로 "아직 기획이나 설계가 마무리되지 않은 상태에서 개발 과정에 대한 마일스톤을 자세히 적는다는 것에 모순이 있는 것 같기도 하고..."라고 생각한다. 이를 해소하기 위해서 설계나 명세화 이전 단계에서 가정할 수 있는 '설졔적인 개념'이 오퍼레이셔널 컨셉트인데, 최상위 컴포넌트와 이들 간의 관계, 이들 내부의 작동 원리 등은 계획 단계에서 가정할 수 있다.

정리하면,
* 메타적 활동, 관리적 활동, 사전 단계 활동을 빼라. 물론 인지하고 운용의 묘 차원에서 넣는 것은 인정.
* 설계나 명세화가 이루어지기 전에도 오퍼레이셔널 컨셉트 수준에서 컴포넌트를 정의하고 작동 원리를 안다고 가정하고 적으면 마일스톤이 "요구사항명세화-설계-개발-테스트"로 뻔하게 구성되는 것을 막을 수 있다.

이상을 감안해서 새로 한 번 적어보기를. "기본 구성 요소간 인터페이스 정의와 최소 기능 개발"는 너무 메타적이다.

**Comment by 9beach** [comment]
@oldiron-ho , 고칠 것이 많지만 일단 내가 작성해봤다.

# 프로덕트 명세화

요구사항 및 기능 명세화, 메뉴와 컨트롤을 포함한 전반적 UX 확정 및 탑레벨 아키텍처.

## 산출물과 종료 조건

요구사항, UX, 시스템 모델 및 탑 레벨 아키텍처 승인.

# 에디트 컴포넌트 v0

API 명세화 및 아래의 기능 구현.
* 커스텀 CSS
* 교정 정보 팝업 윈도우
* 교정 메뉴
* 교정 문자 밑줄 및 교정

## 산출물과 종료 조건

* 에디티 컨트롤 API 승인
* 구현된 기능 시연 및 테스트

# h-draft v0

웹 컴포넌트, 일렉트론, 로컬 노드 모듈 간의 아키텍처 명세화, 플러그인 API 명세화 및 아래의 기능 구현.
* 로컬 파일의 내용을 에디트 컴포넌트 v0에 로드
* 한스펠을 이용해서 에디트 컴포넌트 내용 수정
* 에디티 컨트롤 v0 기능와 h-draft v0 메뉴를 연결

## 산출물과 종료 조건

* 웹 컴포넌트, 일렉트론, 로컬 노드 모듈 간의 인터렉션이 리비전된 아키텍처와 시스템 모델 승인
* 플러그인 API 승인
* 구연된 기능 시연 및 테스트

# 맞춤법 인덱스 v0

API 명세화 및 전 기능 구현

## 산출물과 종료 조건

* API 승인
* 구연된 기능 시연 및 테스트(특히 성능 테스트)

# h-draft v1

위의 기능 통합해서 테스트하고 이후에 지속적으로 개선.

**Comment by oldiron-ho** [comment]
내용을 보니, 마일스톤에 요구되는 게 어떤 건지 감은 오네.
하지만, 많은 용어들이 들으면 "아! 그런 뜻이지. 명료하네." 하는 생각은 들지만, 내가 적으라고 하면 적기 어려웠을 표현인거 같음. 예를 들면 '시스템 모델및 탑 레벨 아키텍쳐 승인',' 모듈 간의 인터렉션이 리비전된 아키텍처와 시스템 모델 승인' 같은거. 
표현이 이상하다는 것이 아니라, 내가 그런 소프트웨어 개발기획 표현에 익숙하지 않다는 뜻임. 

에디트 컴포넌트, h-draft, 맞춤법 인덱스 등을 이 단계에서 정의 됐다고 보고 쓸 수 있다는 것도 처음 마일스톤을 작성해봐야지 할때는 미쳐 생각못했던 거고.

산출물과 종료조건이 명확하게 표현되는 것과 기획 시점에서 마일스톤의 범위를 어디까지 다룰 것인지에 대해서도 참고가 많이 됐음.

**Comment by oldiron-ho** [comment]
프로덕트 명세화와 관련이 있겠지만, 마일스톤에 올라온 내용에 대해서 얘기해 보자면,
1. 커스텀 css 는 기능 구현에서 우선순위가 뒤로 밀린다고 생각함. 모듈간 인터렉션에 관련된 기능을 우선적으로 구현하는 것이 좋을거라고 생각함.
1. 파일 불러오기와 저장기능을 넣고, h-draft 에서 작성된 텍스트에 서식 정보가 포함된다면, 아웃풋
형식을 어떻게 할지에 대해서도 결정을 내릴 필요가 있어 보임.

**Comment by 9beach** [comment]
Ok, 나도 순서는 언제든지 바뀔 수 있다고 생각함. 서식은 draft 리치 에디트 복사해서 딴데 붙여보면 호환되니 아마 rtf 지원하지 않을까... 더 나가서 마크다운으로 저장. 이런 기능도 가능하고... 이런 것 자체가 모두 기능 명세에 포함됨. 앞으로 논의는 슬랙에서 하자. 그리고 저거 개선하고 그다음 이슈로 정의하자.

**Comment by oldiron-ho** [comment]
위키에서 정리하기로 함.
