### ISSUE TITLE
개발 정책 만들기

### ISSUE THREAD

**Issue by oldiron-ho** [9hobbes/h-draft#3]
개발 정책 작성해서 위키로 정리하는 것에 대해서 일정을 정해봅시다.
이번주 동안(주말까지) 초안 작성을 완료하고, 추석이 포함되어 있는 다음주까지 
리뷰와 수정을 완료하는게 좋을거 같습니다. 
그 이후에 개발에 들어갈 수 있게.

현재 위키 제목 기준으로 작성하기로 한 내용은 
@oldiron-ho
* 이슈 트래커 이용
* 커밋, 테스트, 풀 리퀘스트
* 깃 사용
* 풀 리퀘스트 절차

@9beach
* 테스트 방법
* 바이너리 배포 절차
* 바이너리 네이밍 룰 및 버전 체계
* 깃헙 IO를 통해 서비스될 문서 형식

입니다.

**Comment by 9beach** [comment]
내용은 동의하고, 단 이 이슈는 일종의 메타 이슈라서 메타적 체계를 이슈 안에 허용하는 것 보다 위키에 정리하는 것이 나을 것 같다. 만약 준비 단계의 일도 이슈로 처리하고 싶으면 그것 또한 정리해서 마일스톤을 먼저 만들고 근미래 마일스톤 안에 한꺼번에 여러 이슈를 만드는 것이 좋을 것 같으며, 그 정리 장소는 위키가 나을 것 같다. 즉 어떤 경우에도 마일스톤을 먼저 만드는 게 논리적으로 나아 보인다는 말.

**Comment by 9beach** [comment]
더불어, 단락 나누기가 아니라면 엔터를 치는 것은 잘못된 관행. 위에서 "개발 정책 작성해서 ... 수 있게."까지 모두 엔터를 제외해야.

**Comment by 9beach** [comment]
따라서 이 이슈는 닫고 위키 시작 페이지에 적는 것이 나아 보임. 유지하고 싶으면 이슈를 많이 만들어야 할 듯.

**Comment by 9beach** [comment]
https://github.com/9hobbes/h-draft/wiki/바이너리-배포 수정.

**Comment by 9beach** [comment]
여기에 글 달면 노티가니 알림판으로 쓰자. https://github.com/9hobbes/h-draft/wiki/사용자-문서 만듬.

**Comment by oldiron-ho** [comment]
https://github.com/9hobbes/h-draft/wiki/%EA%B9%83-%EC%82%AC%EC%9A%A9
https://github.com/9hobbes/h-draft/wiki/%ED%92%80-%EB%A6%AC%ED%80%98%EC%8A%A4%ED%8A%B8-%EC%A0%88%EC%B0%A8
문서 만듦.

**Comment by oldiron-ho** [comment]
이슈 트래킹에 대해 수정했음. 쓰다가 보니 관점의 차이가 명확해 지는거 같아서 이야기 해보면...
나는 이슈 트래커에 대해서 주제 게시판이라고 판단하고 있음. 메타니 뭐니 따질 필요 없이 이 저장소와 관련된 모든 이슈를 다루고 토론하면 된다고 생각함. 관리가 필요하지 제약이 필요한 공간은 아니라는 이야기.

메타라는 이유로 위키에서 토론하는 것은 형식과 실효성 측면에서 모두 만족스럽지 않음. 우선 맥락에 따른 기록이 남지 않고 찾아볼려면 리비전을 뒤져야하며 1차 작성이 완료된 후 정책변경으로 편집 이슈가 있을때도 거기서 토론을 해야 하냐에 대해서 생각해 보면 이상하다고 생각함.
내 생각은 https://gist.github.com/9beach/dde37e22437642bb4f1f7f2afb208669 에서 제시한 이야기는 프로젝트 보드에 속하는 이슈에 대해서만 제한해서 다루면 된다고 생각해.

현재 여기 관련된 사람이 두사람에 불과하지만 잘모르는 몇명이 추가로 참가하고 사용자가 생긴 이후를 시뮬레이션 해보더라도 메타에 관련된 이슈를 여기서 다룰수 없다면, 이 프로젝트를 진행하는 보드를 따로 만들어서 이중구조로 유지해야 한다는 결론이 나옴.

**Comment by 9beach** [comment]
내 말은 다시 인용하면, "내용은 동의하고, 단 이 이슈는 일종의 메타 이슈라서 메타적 체계를 이슈 안에 허용하는 것 보다 위키에 정리하는 것이 나을 것 같다. 만약 준비 단계의 일도 이슈로 처리하고 싶으면 그것 또한 정리해서 마일스톤을 먼저 만들고 근미래 마일스톤 안에 한꺼번에 여러 이슈를 만드는 것이 좋을 것 같으며, 그 정리 장소는 위키가 나을 것 같다. 즉 어떤 경우에도 마일스톤을 먼저 만드는 게 논리적으로 나아 보인다는 말."

자 위에서 말했듯이 메타 이슈라서 절대 이슈로 만들면 안된다는 말이 아니라 일단 정리하자, 위키에서 했으면 좋겠다, 만약 이슈로 하고 싶으면 근미래 마일스톤에 한해 여러개를 만들자. 즉 생각날때마다 하나씩 만들면 안된다는 걸 강조하고 있음. 위키가 나을 것 같다고 했지 위키에서 해야된다고 말하지 않앗고. 즉 어떤 경우에도 가령 프로젝트 준비 단계 조차도 이슈로 하고 싶으면 (실제로 그것은 좋은 생각임) 준비 단계의 이슈를 정리해서 필요한 백로그를 뽑아서 하자는 말.

즉 백로그는 그것이 준비 단계든 개발 단계든 생각날 때마나 하나씩 뽑으면 안되고 정리해서 추가하자는 말임. 만약 이 최초의 논의조차 이슈로 하고 싶으면 (나는 정말 최초는 위키나 오프라인을 선호하지만, 이슈도 반대하지 않음) 예외적으로 최초 논의라는 이슈를 만들일이지, 지금 생각나는 "개발정책만들기" 단 하나는 아니라는 말.

**Comment by 9beach** [comment]
추가로 이야기하면 내가 다니는 회사도 그렇고, 위키 문서에 대해 이슈를 만들어서 논의하는 식으로 진행하는 것이 베스트 프렉티스 인 것 같다. 논의를 이슈에서 하는 것은 자연스럽고... 단지 "만약 준비 단계의 일도 이슈로 처리하고 싶으면 그것 또한 정리해서 마일스톤을 먼저 만들고 근미래 마일스톤 안에 한꺼번에 여러 이슈를 만드는 것이 좋을 것 같으며" 이 부분을 원칙적으로 강조한 말임.

**Comment by 9beach** [comment]
<https://github.com/9hobbes/h-draft/wiki/이슈-트래커-이용>에 대한 코멘트

* 활동과 대상에 따른 분류로 이원화 한 것이 레퍼런스가 있는지 궁금하다. 그 둘은 기묘하게 오소고널하지도 뮤추얼리 익스클루시브하지도 않다. 오소고널하면 복수의 태깅이 자연스러워야 되는데 그렇지 않고, 그렇지 않다면 뮤추얼리 익스클루시브해야 되는데 또 따져보면 논리적으로 오소고널하다.
* 처음에는 이해가 잘 안됐는데, "버그 보고 , 새 기능 제안, 백로그"라는 상위의 범주를 두고 그 밑에 이슈 타입과 템플릿을 정하는 식으로 생각을 진행한 것 같은데, 상위 범주가 하위를 포괄하지도 못한채 단지 템플릿 종류를 맨처음 이야기하고 이슈 타입과 다시 템플릿을 이야기하는 형식이라 논리적으로 이상함. 그냥 이슈 타입을 정리하고 이슈 타입의 하위 카테고리로서 템플릿이 필요한 경우도 있다 정도가 맞아 보임. 그런 뜻에서 템플릿 페이지도 따로 구분하는 것이 부적절해 보임.

**Comment by 9beach** [comment]
<https://github.com/9hobbes/h-draft/wiki/깃-사용>에 대한 코멘트:

* 뉴피처와 이슈는 일단 논리적으로 이상함. 이슈가 상위 범주이니, 즉 모든 커밋은 그 커밋을하게 만든 이슈가 있어야 하니 니 의도대로라면 뉴피처와 버그라야 함.  그런데 이렇게 할 경우 태스크, 독 등의 타입에 대한 것은 어떻게 하는지 애매함. 만약 니 의도가 뉴 피처(최초의 구현)과 픽스였다고 해도 여전히 최초 구현과 고친 구현을 구분해야 하는지 의문임. 나도 이런 레퍼런스를 봤는데 대부분 의미없는 구분이었고 그렇지 않다면 더 정교했던 것 같애.
* 취지는 공감하나 한 번에 하나만하나만 해라는 표현은 레퍼런스를 못 봤음. 아토믹해라는 표현이 더 적절.
* "Readme.md 파일 수정"은 좋지않은 예시인듯. 오타 수정, 무슨무슨 내용 추가 등으로 관련 이슈를 압축적으로 표현하는 게 좋을 듯.

이상 내가 올린 4개의 댓글에 대해 의견바란다.

**Comment by oldiron-ho** [comment]
이슈트래커와 위키의 문제에 대해서 이야기 해보자면 이 이슈의 제목을 잘못단 것은 나의 실수로 인정함. 실제 내가 하려던 것은 "개발 정책 만들기" 가 아니라 개발정책은 각자 만들건데 그 일정에 대해서 정리해 보자 정도니까. 내용을 보면 의도가 전달될 거라고 생각하고 제목에 큰 의미를 두지 않은것도 사실이고,
그런 의미에서 개발정책이 단일한 것이 아니라 각자 분야가 있으니 그걸 백로그로 만들어서 각각 이슈로 토론할 수 있다라는 얘기로 한거라면 나도 그렇게 하면 된다고 생각함. 그런 의미에서는 입장차가 없다는 생각이 드네. 나는 이슈트래커의 활용을 협소하게 정의하고 개발 과정 전에서는 이슈트래커를 쓰면 안된다는 입장을 가지고 있는건가 하는 생각을 하고 있었음.
그렇다면 지금에 와서는 어떻게 하는 것이 좋을것인가 하는 문제가 남는데....
이미 진행이 꽤 된 상태라 마일스톤 정의 -> 백로그 도출 과정을 지금이라도 해야 되냐라는 판단을 해야 될거 같은데 솔직히 잘 모르겠음. 할수도 있지만 현재 정의된 정책 분야에서 리뷰-수정만 하면 되는데 괜히 일을 더 벌리는 것 같고, 안한다면 이 이슈에 이런식으로 리플 꼬리 달기를 할거 같은데 그것도 좀 이상하고.

그외  다른 리뷰에 대한 이야기는 시간 날때 다시 해야 할거 같음. 명절이라.

**Comment by 9beach** [comment]
OK. 니 말대로 지금 또 번거롭게 하느니 지금대로 진행해서 정책 여기서 토론하며 다 정하고 마일스톤, 근미래 백로그 정하기로 가는 게 좋겠다. 그리고 이런 "생각" 저런 "생각"에 대해 토론하는 자리에 굳이 실수를 인정할 것 까지야. ㅎ

**Comment by 9beach** [comment]
내 스케줄을 밝히자면, 일단 남은 것은 "테스트 방법" 작성하는 것인데, 내가 남들 보고는 테스트 체계를 온전히 가지고 있는 보일러플레이트 프로젝트를 작성한 뒤 프로젝트를 진행하라고 하지만, 스스로는 `draft.js` 작동하는 거 보고 싶어서 일렉트론 프로젝트 공부하지 않고 일단 올렸거든. 여러모로 좋지 않은 선택인 듯. 결국 제대로 그리고 저비용으로 진행하려면 일렉트론으로 보일러플레이트 프로젝트를 만들어야 유의미한 "테스트 방법"을 작성할 수 있을 것 같아. 이것은 공부를 좀 해야해서 시간이 꽤 걸릴듯. 하루 종일 한다면 하루이틀 걸리겠지만 지금처럼 쉬엄쉬엄하면 다음주 말 정도에 나올 듯.

그러니 지난 번 니가 손 본 마일스톤 마무리해서 정리하는 일과 병행해서 할께. Ok?

**Comment by oldiron-ho** [comment]
진행과 일정에 대해서 동의!

**Comment by oldiron-ho** [comment]
https://github.com/9hobbes/h-draft/wiki/이슈-트래커-이용에 대한 코멘트에 대해 답하자면 

* 이슈타입(레이블)에 대한 비판은 거의 맞고 정교하게 작성된 것도 아님. 문서에 설명했듯이 이슈타입에 대해서 해쉬태그에 가깝다고 판단하고 있으며, 중요한 구분은 프로젝트 보드에 들어가는 task 냐 그 외 게시판 태그처럼 쓰는 레이블이냐에 있고 그외에는 범주가 중요하지 않고, 필요에 따라 추가하면 된다는 입장이야. 범주는 이런 것도 들어 갈 수 있지 않을까 하는 사례예를 든거에 가깝고.
* 프로젝트에 대해 평가에 필요한 메트릭을 정의하고 그것을 측정하기 위한 도구로 정교하게 정의된 레이블을 이용할 수 있다고 생각하는데 그쪽으로는 경험이 없어서 더 고민하거나 찾아보지는 않았음.
*  이슈 작성 템플릿은 사실 그리 큰 비중이 없고 편의 제공에 가까운데 문서의 맨 위 항목에 있어서 오해를 불러일으키는 거 같음. 전체적으로 편집과 내용에 대해서 좀 더 수정을 할 예정임.  
* 이슈 타입에 대해서 다른 프로젝트도 꽤 혼란스럽더라고. 최소로 정의한 곳도 있고 마구 늘려서 100여개가 넘는 데도 있고.  난 최소로 시작해서 큰 고민하지 말고 필요하면 늘리자라고 생각하고 있음. 이에 대해 좋은 예나 생각 있으면 얘기해주면 좋겠네.

**Comment by oldiron-ho** [comment]
https://github.com/9hobbes/h-draft/wiki/깃-사용에 대한 코멘트에 답하자면

* 기본구상은 https://mirocommunity.readthedocs.io/en/latest/internals/branching-model.html 에 나오는 명명법에 착안을 한건데, 문서는 git-flow 브랜치 전략을 반영하고 있다고 생각함. 그런데, 우리는 마스터 브랜치를 개발 메인 브랜치로 이용하는 거니까 여기에서 제기한 4가지 케이스를 그대로 쓸 이유가 없어 보여서 뉴피처를 그대로 두고 나머지 bugfix, hotfix, release 와 관련된 것들을 단일 issue 라는 단위로 묶어서 쓰는게 어떨까 하는 것이었음. 실제 피쳐로 명명되는 것은 여러 이슈의 결합일 가능성이 높으니 이슈번호가 필요없는 피쳐명으로 이름을 만들고 그외에는 이슈별로 브랜치를 만들어서 이슈번호가 명시되는게 좋겠다는 판단임.
* 위와 관련해서는 더 토론이 필요한거 같고, 그외 지적에 대해서는 적절한 지적이라고 생각하고 수정에 반영할게.

**Comment by 9beach** [comment]
이슈 트래커에 대한 니 의견과 계획에 모두 동의.

내 의견을 말하자면, "분류를 위한 분류는 없어야 된다." 딱 이거 하나. 서양사람들과 동아시아 사람이 극단적으로 갈라지는 지점이기도 함. 프로세스와 연계되어 사용되지 않는 이슈 타입은 만들 필요가 없음. 이상한 이슈 타입을 만들때마다 내가 자주 하는 이야기는 "우리 와이프가 좋아하는 단어가 들어가는 이슈"라는 이슈 타입을 만든 것과 무슨 차이냐... 

스크립팅을 통해 이슈 타입을 보고 무언가를 하는 경우가 아니라면(가령 들어온 이슈의 스테이트를 나누어서 드래프트다 컨펌드다, 또는 컴포넌트별로 구분해서 어싸이니를 자동으로 할당하기 위해 js 다 css다, 등등...) 굳이 분류할 필요는 없으나, 우리가 이슈 제목을 적는 방법 내용을 적는 방법을 강제하기 위해서는 전체 집합을 정의하고 형식이 강제된 대상을 지정할 필요가 있거든...  따라서 분류할라고 애쓰지 말고 이슈를 지 맘대로 적는거를 막는다는 관점에서 분류하면 될 것 같애. 우리는 스크립팅하거나 스테이트 변환 안할 테니... 특히 프로젝트 보드를 쓰기로 했으니 더더구나 스테이트가 필요없지...

니가 좋은 예를 달라고 했지만 난 이런 수준의 요건만^^ 굳이 억지러 정하자면 버그와 피처 두개로 나누고 두개가 템플릿이 어떻게 다른지 플로우가 어떻게 다른지 정하면 될 듯... 스테이트나 컴포넌트를 레이블화하려면 역시 마찬가지로 플로우를 정의하고 템플릿을 정의하는, 즉 그것을 활용하는 절차를 선행해서 정하면 될 듯.

**Comment by 9beach** [comment]
두번째 코멘트는 모두 Ok

**Comment by 9beach** [comment]
브랜치 네이밍과 이슈 타입이 연관이 있네... 생각할수록 베스트 프랙티스 만드는 게 난이도 있네. 좀 찾아봐야 할 듯.

**Comment by 9beach** [comment]
https://barro.github.io/2016/02/a-succesful-git-branching-model-considered-harmful/

**Comment by oldiron-ho** [comment]
위에서 나온 이야기를 반영해서 위키 문서에 소소한 수정을 했음. 실제 필요한 것 보다 최소한만 수정을 했는데 이 이야기가 더 중요할 듯 해서 더 풀어보자면...
정책을 위키로 작성하는 작업이 길어지면서 이 프로젝트에 대한 관심과 흥미가 급격히 감소하고 있다고 느끼고 있음. 별거 아닌 수정이지만 쉽사리 손이 안가는 것도 그 이유가 크고. 
수정하려고 에디터를 키면 멍해지면서 "하기 싫다."라는 생각만 드는 상황임. 덕분에 다른 일들도 같이 버퍼링에 걸리고 있고.

프로그램을 보일러플레이트로 시작하듯 정책도 좋진 않지만 겨우 돌아가는 정도라도 시작하는 게 어떨까 생각함. 프로그램을 고쳐 나가듯 정책도 실제 발생하는 문제에 대한 수정을 거치면서 좋아질 수 있으니까.
나에게는 깃 사용, 프로덕트 개발, 오픈소스 개발 같은 요소들이 거의 처음이라서 정책에 대한 경험적 레퍼런스가 없거나 부족한거 같음. 그래서 베스트 프랙티스를 시뮬레이션을 통해서 찾아야 하는 상황인데 한계가 뚜렷한거 같고.

여튼 요지는 정책에 대한 수정은 더 이상 못하겠다.  지금 고치지 않으면 당장 프로젝트가 안돌아갈 만한 것만 아니면 우선 시작하고 트라이얼&에러로 고쳐나가자.

**Comment by 9beach** [comment]
Ok, 나도 동의!

**Comment by 9beach** [comment]
그럼 이제 뭐할까? 보일러 플레이트? 아님, 백로그? 둘 중 하나일것 같은데... 니가 원하는 것 선언하고 하기를..
